### ISSUE TITLE
Stray pixels are visible after startup

### ISSUE THREAD

**Issue by bjaan** [bjaan/roland-juno-g-display-replacement#1]
In order to avoid a full redraw of the screen, which is slow, for every frame, a back buffer is added in the code. 

```c
volatile uint16_t buffer_cs1[12*123];
volatile uint16_t buffer_cs2[12*123];
volatile uint8_t back_buffer_cs1[12*123];
volatile uint8_t back_buffer_cs2[12*123];
```

The code will check it before setting the pixel on the display and will do so when it differs.

e.g. for _CS1_:
```c
if (back_buffer_cs1[i] != val) {
  ...
  if ((val & 0x1) == 0x1) tft.drawPixel(x, y, TFT_BLACK); else tft.drawPixel(x, y, TFT_WHITE);
  ...
}
back_buffer_cs1[i] = val;
```

For an unknown reason, this back buffer logic will cause some pixels to stay lit after the boot-up sequence of the JUNO-G.

Switching and backing out of the ARPEGGIO screen will clear most of them.

The problem does not occur during normal operation. Just at start-up.

![screen_sparkles](https://user-images.githubusercontent.com/42038171/207978309-2a10b9cd-f093-41d9-8cd8-8df57082b10e.jpg)

**Comment by dpeddi** [comment]
I also did some attempt like you but I suspended due to lack of time. 

You didn't considered/noticed that the keyboard sometimes send a 0xa0/0xa1 command needed by ks0108. Roland should have used to avoid visible sweep of the LCD...
You can look at the csv and the python code and you should see that in the log.

I think these bytes creates some misalignment in the dma buffer. I'm sure it's the cause of your trouble.

Maybe is possible to filter out that commands in the pio code, or you should apply some logic to count them and increase the index when you check the backbuffer.

**Comment by bjaan** [comment]
Thanks. I think you're correct. 

As I am still putting things together and see if I can make an improvement, I went to look for reference materials of the protocol, and the ks0108 display controller. I found related stuff for displays with different resolutions, the JUNO-G one is 240x96, while most examples are for 128x64.

1.  two C/C++ drivers that write to the related ks0108 display controller, and it not uncommon to have multiple CS lines it seems..

![image](https://user-images.githubusercontent.com/42038171/208217778-2ebfde8a-609b-4a26-be80-31600096d70d.png)
![image](https://user-images.githubusercontent.com/42038171/208248776-915dd74b-887d-4993-ac0f-1a41e729b3c1.png)
![image](https://user-images.githubusercontent.com/42038171/208249901-f7849390-696f-4f6b-90f2-c6f268ef7714.png)

The library https://sourceforge.net/projects/serdisplib/ describes a "time-saving algorithm":

```c
/* *********************************
   void serdisp_ks0108_update(dd)
   *********************************
   updates the display using display-buffer scrbuf+scrbuf_chg
   *********************************
   dd     ... display descriptor
   *********************************

   the display is redrawn using a time-saving algorithm:

     background knowledge: after writing a page-entry to the display,
     the x-address is increased automatically =>
     * try to utilize this auto-increasing
       (if a whole horizontal line needs to be redrawn: only 4x PutCtrl per page will be needed)

     * on the other hand try to avoid writing of unchanged data: 
       best case: no need to change any data in a certain page: 0x PutCtrl (set page) + 0x PutCtrl (set xpos) + 0x PutData)
```
and http://www.piclist.com/techref/microchip/language/c/ks0107.htm

and it seems that RS or DI stands for DATA or INSTRUCTION (INSTRUCTION/DATA REGISTER SELECTION) and that you indeed did use RS register as described in the datasheet

```
RS = 0 : INSTRUCTION REGISTER
RS = 1 : DATA REGISTER
```
As it is still a mystery to me how the data buffers are filled using PIO, I am going to assume it is correct how RS gets determined.

Also when RS is 1 in your code it did check for the set X (line) instruction....

![image](https://user-images.githubusercontent.com/42038171/208246374-955bd85b-bc1d-4408-9087-8d664ce93606.png)

Code from another library to control the ks108
```
void lcd_setpage(unsigned char page)
{
    _lcd_waitbusy();
    DI=0; RW=0; 
    LCD_DATA = 0b10111000 | page;
    _lcd_enable();
}

void lcd_setyaddr(unsigned char y)
{
    _lcd_waitbusy();
    DI=0; RW=0;
    LCD_DATA = 0b01000000 | (y & 0b00111111);
    _lcd_enable();
}

void _lcd_waitbusy(void)
{
    while (_lcd_status() & 0b10000000)
    {
        Delay10TCYx(250); // .5 ms
    }
}

void lcd_write (unsigned char data)
{
    _lcd_waitbusy();
    DI=1; RW=0;
    LCD_TRIS=0; 
    LCD_DATA = data;
    _lcd_enable();
}

void lcd_selectside(unsigned char sides)
{
    // set a CS pin low to enable it
    if (sides & LEFT)
        CS1 = 0;
    else
        CS1 = 1;

    if (sides & RIGHT)
        CS2 = 0;
    else
        CS2 = 1;
}

unsigned char lcd_read (void)
{
    unsigned char _data;
    
    LCD_TRIS=0xFF;
    RW = 1; DI=1;
    _lcd_enable();
   _data = LCD_DATA;
   LCD_TRIS=0x00;
   return _data;
}

void lcd_plotpixel(unsigned char rx, unsigned char ry)

   unsigned char data;
   //lcd_waitbusy();
   // select the correct side
   if (rx & 64)
       lcd_selectside(RIGHT);
   else
       lcd_selectside(LEFT);

   lcd_setpage( ry >> 3);
   lcd_setyaddr( rx & 0b00111111);
   data = lcd_read(); // dummy read needed here
   data = lcd_read();
   lcd_setyaddr( rx & 0b00111111); 
   lcd_write (data | (1 << (ry & 0b111)));
}
```
2. explanations how the controller works and how to build a project to control the ks0108 controller
https://exploreembedded.com/wiki/Graphics_LCD_Basics_:_KS0108_based_JHD12864E
Datasheet: https://www.engineersgarage.com/wp-content/uploads/2019/10/Graphics-LCD-JHD12864E-Datasheet.pdf
https://embedded-lab.com/blog/lab-20-interfacing-a-ks0108-based-graphics-lcd-part-1/
http://www.enduco.com/GLCD%20Docs/GLCD_Doc1.pdf

![image](https://user-images.githubusercontent.com/42038171/208243828-5f72fc78-4f4f-451d-aeb7-bec95c822f3e.png)

![image](https://user-images.githubusercontent.com/42038171/208218909-ecb22c0c-3cd6-4e4a-af5a-f1aa09493572.png)

![image](https://user-images.githubusercontent.com/42038171/208250189-83044d4c-0cb6-494b-94a3-abcf0cedd46f.png)

------
So if we split the LCD in two parts, we would get 64x64 pixels in the examples and the Y register of 8 bits just fits 64 and the X (page) register of 3 bits (max. 7 * 8 pixel rows of 8 pixels),
| X (page) register | start | finish |
|---|---|---|
| 0 | 0 | 8 |
| 1 | 8 | 16 |
| 2 | 16 | 24 |
| 3 | 24 | 32 |
| 4 | 32 | 40 |
| 5 | 40 | 48 |
| 6 | 48 | 56 |
| 7 | 56 | 64 |

However when we split the JUNO G display in parts it would result into 120x96 pixels, and that column X of 3 bits is therefor too small.

[dpeddi](https://github.com/dpeddi) already found that Roland is using a modified version of the set X (line) instruction.... as it using a 4 bit X register, also the Y (column) register of 6 bits does not fit (max 64 columns and not 120) and dpeddi also found that it goes up to 120, so maybe there is no instruction to set this or it is using that set address command with an extra bit.

I made list of de pin numbers currently used in PIO

PIO pins:

| bit position | JUNO-G Pin | Raspberry Pi Pico Pin | pin_offset |
|---|---|---|---|
| 15 | D0 | GP2 | 0 |
| 14 | D1 | GP3 | 1 |
| 13 | D2 | GP4 | 2 |
| 12 | D3 | GP5 | 3 |
| 11 | D4 | GP6 | 4 |
| 10 | D5 | GP7 | 5 |
| 9 | D6 | GP8 | 6 |
| 8 | D7 | GP9 | 7 |
| 7 | WE (enable?) | GP10 | 8 |
| 6 | RS D/I | GP11 | 9 |
| 5 | CS1 | GP12 | 10 |
| 4 | Cs2 | GP13 | 11 |

And I did try to reproduce the issue in Python using dpeddi script and data:

![image](https://user-images.githubusercontent.com/42038171/208301411-9ce95c45-1bda-4d6e-9610-449033a09550.png)

But the effects are different.

So still a work-in-progress

**Comment by bjaan** [comment]
Resolved in v0.5.

First resolved in Python [parse_sdl2-fixed.zip](https://github.com/bjaan/roland-juno-g-display-replacement/files/10256150/parse_sdl2-fixed.zip) and then the trick worked in C++ on the Pico.

The issue was resolved by using a properly dimensioned back buffer for the entire original display.

Performance is even better now as other updates have been done as well, such as a pre-calculated pixel coordinates matrix to match original display coordinates with the new display's coordinates.  This allows a simple memory lookup rather than a display coordinate calculation for every pixel for every frame.

Thanks!

**Comment by dpeddi** [comment]
So finally you get performance improvement?
Did you still have the glitches?

**Comment by bjaan** [comment]
Yes, the performance is perfect now (v0.5), a full screen update only takes a fraction of a second, much less than it did originally.  I do no longer see any screen tearing (maybe just barely and for very short periods when lots of things change, like very quickly scrolling through the presets)

All updated code is pushed to this repository.

One *very* small issue is that the very first frames, during start-up, are not rendered correctly, where the Roland logo appears during the beginning of the startup, as it appears "hollow" and then everything is just fine in less than a second, when the JUNO-G logo start spinning, from then on there no glitches or stray pixels, like in the first post :-) I suspect I didn't initialize the back buffer properly in C++.

Here is a short video while trying out the filter section where the Pico is running the latest version (v0.5)

https://user-images.githubusercontent.com/42038171/208516414-54630265-3045-47cd-accd-c8d72eb0dfbc.mp4

The keyboard is closed now.

**Comment by dpeddi** [comment]
As on original readme, probably the controller was a KS0713 and not a ks0108.

**Comment by bjaan** [comment]
Must have missed that.  Oh yeah that makes sense it was a KS0713. Just checked its documentation.

Then the setting of the X and Y coordinates makes sense to me.  I saw a lot of 0x10/0x00 instruction bytes in the data in Python.  Typicall after the 0xb? instruction.

0x10/0x00 must be a pair of commands where it setting the _Column Address_ bits
0x10 = Set Column Address MSB to 0
0x00 = Set Column Address LSB to 0
Where it must setting after calling the _Set Page Address_ instruction


Page 39 of the document linked below:
![image](https://user-images.githubusercontent.com/42038171/208528224-038f983d-e543-4f53-8a69-3a981153cdaf.png)

Page 38 https://www.lcd-module.de/eng/pdf/zubehoer/ks0713.pdf
