### ISSUE TITLE
Line 20 of platformio.ini is preventing the code from being built

### ISSUE THREAD

**Issue by HiImCris** [bjaan/roland-juno-g-display-replacement#4]
> platform_packages = earlephilhower/tool-pioasm-rp2040-earlephilhower@^5.100300.220714

That line is causing an UnknowPackageError, as that repository no longer exists. Since the original code has that line commented out, I believe removing it won't hurt the firmware and will have it built.

EDIT: Why would anyone want to build it when it's already built in this repository? I wanted to change the colors. That's why.

**Comment by bjaan** [comment]
I changed the line to _platform_packages = earlephilhower/tool-pioasm-rp2040-earlephilhower_
and Build action seems to work after a Full Clean action

**Comment by bjaan** [comment]
Closing.
